### ISSUE TITLE
Authentication functions

### ISSUE THREAD

**Issue by AaronBuxbaum** [urish/protractor-firebase#2]
For my purposes, I need authentication (users must log in before they can access any page), and it'd be super convenient to use `protractor-firebase` to mock `$authWithPassword`. MockFirebase doesn't really work super effectively in combination with Protractor, unless I'm missing the proper way to set it up.

**Comment by urish** [comment]
Hi, you may want to check out my other project - [firebase-server](https://github.com/urish/firebase-server), which also supports authenticaton
