### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by pdesgarets** [urish/protractor-firebase#5]
Hi,
Is bumping version number planned soon ?
Thanks !

**Comment by urish** [comment]
Perhaps are you interested in maintaining this package?

**Comment by pdesgarets** [comment]
Sorry, I didn't mean to be insistant. I'd be just glad to help as much as I can and as long as I have some time for this, if it is through having the "npm publishing privileges" myself, then let's do it :)

**Comment by urish** [comment]
Great! What is your email address?

**Comment by pdesgarets** [comment]
You can use pdesgarets+github@outlook.com

**Comment by urish** [comment]
actually, it seems like I need your npm username

**Comment by pdesgarets** [comment]
pdesgarets

**Comment by urish** [comment]
done!

    $ npm owner ls protractor-firebase
    pdesgarets <pdesgarets+github@outlook.com>
    urish <uri@urish.org>

**Comment by pdesgarets** [comment]
Great, thanks ! Could you add me as a collaborator with push permissions on github as well, please ?

**Comment by urish** [comment]
Sure, done!

Thanks :-)
